
services:
  web:
    image: php:apache
    container_name: eazylets_web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    container_name: eazylets_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eazylets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
